### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by zc99** [joheras/CLoDSA#14]
![image](https://user-images.githubusercontent.com/69033926/89014991-ee756b00-d348-11ea-92ac-114f96447e49.png)

**Comment by joheras** [comment]
Could you provide an example to reproduce the error?

**Comment by zc99** [comment]
I found the error. It must be "A Folder With Videos" Inside "ANOTHER FOLDER" right?

**Comment by joheras** [comment]
Yes, that is right.
