### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by mchtalkn** [joheras/CLoDSA#16]
https://github.com/joheras/CLoDSA/blob/0b962a6a15989154fba6ca8371a852d6b326d169/clodsa/clodsa/augmentors/cocoLinearInstanceSegmentationAugmentor.py#L132-L134
Could you add mkdir functionality to there.
sth like  `os.makedirs(os.path.dirname(self.outputPath),  exist_ok=True)` might be good

**Comment by joheras** [comment]
Fixed. Thanks for reporting this.
I have been on vacation for two weeks and I could not add this
functionality before.
Let me know if anything else comes in the future.
Best,
Jónathan
