### ISSUE TITLE
sklearn.externals.joblib error

### ISSUE THREAD

**Issue by bractus** [joheras/CLoDSA#18]
When i download CLoDSA from pip i get the 1.2.4 version... the github installs the 1.0.0 version...

There's an error when I try to import sklearn.externals.joblib and I need to replace with from joblib...

Anyone else got this error?

**Comment by dontcryme** [comment]
Solution 1)
[1]pip in joblib
[2]change 'sklearn.externals.joblib' to 'joblib'
Solution 2)
pip install (old)sklearn

**Comment by rivered** [comment]
I applied solution 1, but it requires quite some .py files to be altered from the CLoDSA library as all the augmentations techniques are called upon when loading the library. After changing them it works fine.

**Comment by joheras** [comment]
I have updated the library to work with joblib instead of sklearn.externals.joblib. 
In addition, I have changed the github installation to install the same version. 
Best,
Jónathan
