### ISSUE TITLE
No module named augmentors.augmentorFactory

### ISSUE THREAD

**Issue by PabloDIGITS** [joheras/CLoDSA#2]
Hi:

I have installed the library with the pip command and it shows when I do pip list. Doing import clodsa in python dont give me errors. But when I'm using a script that begins with:
`from matplotlib import pyplot as plt`
`from clodsa.augmentors.augmentorFactory import createAugmentor`
`import xml.etree.ElementTree as ET`
`import cv2`
And I execute it it show me this error:
```
Traceback (most recent call last):
  File "clodsa.py", line 2, in <module>
    from clodsa.augmentors.augmentorFactory import createAugmentor
  File "/home/nvidia/CLoDSA/clodsa.py", line 2, in <module>
    from clodsa.augmentors.augmentorFactory import createAugmentor
ImportError: No module named augmentors.augmentorFactory
```
When I list sys.path (where python looks for packages or modules) it shows a list of paths and I one of them I can find that module. How I can fix this error? 
PD: I'm working for a company in Spain so we can talk in spanish if you want.
**EDIT**
I manage to solve this by adding the root folder of the repository to the sys.path of python 2.7. I did that with the following commands:
```
python
>>> import sys
>>> sys.path.append('/home/nvidia/CLoDSA')
```
Now I have another error when executing my script from above:
```
$ python test.py
Using TensorFlow backend.
[libprotobuf FATAL google/protobuf/stubs/common.cc:61] This program requires version 3.5.0 of the Protocol Buffer runtime library, but the installed version is 2.6.1.  Please update your library.  If you compiled the program yourself, make sure that your headers are from the same version of Protocol Buffers as your link-time library.  (Version verification failed in "external/protobuf_archive/src/google/protobuf/any.pb.cc".)
terminate called after throwing an instance of 'google::protobuf::FatalException'
  what():  This program requires version 3.5.0 of the Protocol Buffer runtime library, but the installed version is 2.6.1.  Please update your library.  If you compiled the program yourself, make sure that your headers are from the same version of Protocol Buffers as your link-time library.  (Version verification failed in "external/protobuf_archive/src/google/protobuf/any.pb.cc".)
Aborted (core dumped)
```
I dont know how to fix this for now. Thanks for help in advance.

**Comment by PabloDIGITS** [comment]
Hi joheras,
I use the library to augment data from 10 images with their label files to 80 images with their modified label files, but I'm not sure if the modified label files are correct. Here is an example with an image flipped vertically:
In the original image labeled with the tool Yolo_mark, the label file is:
`0 0.535547 0.723611 0.911719 0.508333`
In the modified image (CLoDSA library), the modified label file is:
`0 0.529411764706 0.0505050505051 0.911764705882 0.104377104377`
And if I label with Yolo_mark the modified image to see if it is similar to the above, the label file is:
`0 0.528906 0.293750 0.921875 0.559722`
If I understand the YOLO format is : **c**(class) **x**(relative x coordinate of the center of the rectangle) **y**(relative y coordinate of the center of the rectangle) **width**(relative width of the rectangle) **height**(relative height of the rectangle)
In a vertical flip transformation the **x**, **width** and **height** of the rectangle should not change but the **y** can change.
As you can see the **y** coordinate change but the value is near 0, like if the center of the rectangle is in the top border of the image, and the **height** is different too.
Are this differences normal or I am doing something wrong?
Thanks for the help.

**Comment by joheras** [comment]
Hi, 
I think that you might be doing something wrong because those values are really strange. 

I attach you a Jupyter notebook showing how to augment the dataset of images using YOLO:
[clodsaYOLO.zip](https://github.com/joheras/CLoDSA/files/2573130/clodsaYOLO.zip)

Let me know if that works for you. Otherwise, you might send me one of your images and the annotation and I can try to see what is wrong.

Best,
Jónathan

**Comment by joheras** [comment]
Hi, 

there was a bug in my code, and I was considering the width as the height and viceversa, and it worked in my images because there were squares. 

I have uploaded a new version of clodsa with the problem solved, you can install it using
pip install clodsa==1.2.8

Now, you should obtain the correct result. Let me know if that works for you.

Thanks a lot for reporting this problem.
Best,
Jónathan

**Comment by PabloDIGITS** [comment]
Ok, thanks for the effort. I will check it and comment how its going.

**Comment by PabloDIGITS** [comment]
Hi,
Now the problem with the vertical and horizontal flipped images seems to be fixed. The label coordinates make sense. But checking the 90 grades rotated labels I found this coordinates that I think they are not correct. I show the example:
Original image with original labels by Yolo_mark:
![download1](https://user-images.githubusercontent.com/40455065/48405186-b6b83100-e729-11e8-8112-4fac4328bdde.jpg)
[download1.txt](https://github.com/joheras/CLoDSA/files/2575622/download1.txt)
`0 0.535547 0.723611 0.911719 0.508333`
Rotated 90 grades clockwise image by the script with rotated labels:
![0_3_image2](https://user-images.githubusercontent.com/40455065/48405341-0860bb80-e72a-11e8-9fac-e5e40711f43f.jpg)
[0_3_image2.txt](https://github.com/joheras/CLoDSA/files/2575634/0_3_image2.txt)
`0 0.161616161616 0.929411764706 0.292929292929 1.59411764706`

I label the rotated image with Yolo_mark to have a reference and see how the label coordinates should approximately be:
`0 0.301562 0.529167 0.537500 0.916667`
I think there is something wrong with the rotation technique and the label transformation.

**Comment by joheras** [comment]
Sorry, there was another bug computing the size of the generated image and that was the problem. It is fixed now and I hope that there is not any additional bug. 
You can install it the new version using
pip install clodsa==1.2.9

Let me know if that works for you now.

I am just curious about your project, could you send me a private email to joheras@gmail.com? Maybe we could collaborate in some way.

Best,
Jónathan

**Comment by PabloDIGITS** [comment]
Hi Jónathan,
I checked the version 1.2.9 and now everything seems to be OK and the generated labels are correct. Thank you for fixing the bugs and your effort.

**Comment by joheras** [comment]
Great! Let me know if you need further help.
