### ISSUE TITLE
changing background colour during rotation

### ISSUE THREAD

**Issue by pranav7n** [joheras/CLoDSA#20]
Hi @joheras , I used the clodsa package to rotate a few images that I have by a small angle. After the rotation, there were some black portions that resulted from the rotation. I was wondering if there was a method to change the black background to white?

![0_flowchart_25](https://user-images.githubusercontent.com/72755303/95925154-f0f33880-0d6d-11eb-80a8-5d24cd371a0b.png)

**Comment by pranav7n** [comment]
what i mean is, is there a parameter within the method that I can change to set the background to white?

**Comment by rivered** [comment]
Just modify the rotate augment technique py file to specify the background color explicitly
/local directory.... .local/lib/python3.6/site-packages/clodsa/techniques/rotateAugmentationTechnique.py

Replace return cv2.warpAffine(image, M, (nW, nH))
with return cv2.warpAffine(image, M, (nW, nH), borderValue=(255,255,255))

Didn't check if it works

**Comment by pranav7n** [comment]
Yep it works! thank you so much!
