### ISSUE TITLE
readCOCOJSONBoxes non existent

### ISSUE THREAD

**Issue by juanmed** [joheras/CLoDSA#28]
Hi,

Thanks for sharing such an awesome tool to create augmented datasets. I cloned and installed from source but found that  in the cocoLinearDetectionAugmentor there is a, [seemingly incorrect, import of readCOCOJSONBoxes](https://github.com/joheras/CLoDSA/blob/ea272f4303db3746d21e3b6b8d5c629e425bf68a/clodsa/clodsa/augmentors/cocoLinearDetectionAugmentor.py#L7). This method does not exist so I changed it to readCOCOJSON, which does exists. 

I will make a pull request to solve this issue. 

Thanks,

**Comment by joheras** [comment]
Thanks for fixing this issue.
Best,
Jónathan
