### ISSUE TITLE
How to add  background replacement technique for instance segmentation

### ISSUE THREAD

**Issue by juanmed** [joheras/CLoDSA#31]
Hi,

I am looking into implementing the feature requested in #1 for instance segmentation in coco format, this is, given an image and all the instance masks, replace all pixels corresponding to background with pixels from another image. Here, background pixels would be all those pixels that do not correspond to any instance. I am planning to use images from the VOC dataset to replace the backgrounds.

I understand that this technique would be a ***PositionInvariantTechnique*** for which basically only the image is transformed and the masklabels are returned without modification. However, in contrast to the current PositionInvariantTechniques available, this one does need the masklabels when modifying the image, as explained before.

I am failing to understand how implement this using the current structure of Transformer.py, transformerForInstanceSegmentation.py since the transform method assumes that the technique is applied in the  same way and independently for the image and the masklabels using ***technique.apply()***.

Could you please give me some ideas on how to add the background replacement technique for instance segmentation?

Thanks,

**Comment by juanmed** [comment]
I think one solution is to add a new "BackgroundReplaceTechnique" class in technique.py such with a new apply2 (or whatever) method that can receive two parameters, namely "image" and "masklabels", such that the background replacement is possible. Then in the class transformerForInstanceSegmentation, the check would be make using ***isinstance*** to know how to call it.

**Comment by joheras** [comment]
Thanks for adding this feature to the CLODSA library.
