### ISSUE TITLE
Exposure , translation and random crop for YOLO

### ISSUE THREAD

**Issue by Rahul-Venugopal** [joheras/CLoDSA#4]
Hi  @joheras ,

Thanks for this cool repository and I am using this for creating training images for YOLO. I would like to know the possibility of adding **exposure , translation and random crop** to the images . Do you have any transformers which can do this techniques ? 

Hope to hear from you soon

Thanks 
Rahul

**Comment by joheras** [comment]
Hi Rahul,

I am not sure about what you mean by exposure, could you send me an example?

About translations and crops, there are two transformers:
https://github.com/joheras/CLoDSA/blob/master/docs/augmentation_techniques.md#Crop
https://github.com/joheras/CLoDSA/blob/master/docs/augmentation_techniques.md#Translation

Or do you need something else? Could you give me an example of what you will need so I can try to add the new transformers?

Best, 
Jónathan
