### ISSUE TITLE
How to do with yolov5 with xml annotations? 

### ISSUE THREAD

**Issue by IamNaQi** [joheras/CLoDSA#56]
Hi

I am very thankful for your great work. I am facing an issue to how to YOLO format where I have a annotation in xml format.

Like this
# # - Folder
# # |- image1.jpg
# # |- image1.xml
# # |- image2.jpg
# # |- image2.xml
# # |- ...

Please give an example

**Comment by joheras** [comment]
Hi,

Currently, is the yolo v5 xml format the same as PascalVOC? If that is the
case, you can use the code from the following notebook:
https://colab.research.google.com/github/joheras/CLoDSA/blob/master/notebooks/CLODSA_Plants.ipynb#scrollTo=b3fsGvQfafSc

If it is a different format, we have to implement the functionality to
process that kind of xml file.

Best,
Jónathan

**Comment by IamNaQi** [comment]
**You are life saver** 



thank you so much @ @joheras
