### ISSUE TITLE
Different length of boxes

### ISSUE THREAD

**Issue by shaikaz** [joheras/CLoDSA#6]
Hi, 
I tried to run the Augmenting a dataset for object detection in YOLO example, from the notebook examples, on a custom data, and I'm getting an error on different length of the boxes,
some times the length of a box is 2 (label, (x,y,w,h)) and sometimes the lengh is 3 (label, (x,y,w,h), category), anyway it seems that in different places in the code it's not suppose to be like that. Does anyone got into this issue?
Thanks!

**Comment by joheras** [comment]
Hi,
thanks for the bug report, it is fixed in the new version of clodsa. Please install it using:
pip install clodsa==1.2.32
That should solve the problem.
Let me know if that works for you.
Best,
Jónathan

**Comment by shaikaz** [comment]
Hi @joheras,
It's working now, Thanks!
Shai
