### ISSUE TITLE
Can't parse 'pt1' / 'rec' Error - COCO Detection 

### ISSUE THREAD

**Issue by Natriumpikant** [joheras/CLoDSA#74]
Hello,

I try to edit a COCO **Detection**-Dataset with CLoDSA.

If i run the following notebook, it works very well:
[https://colab.research.google.com/github/joheras/CLoDSA/blob/master/notebooks/CLODSA_COCO_Detection.ipynb](url)

If i run the same code with my data, i get the following error ( on gc and also local ):

>  - Can't parse 'pt1'. Sequence item with index 0 has a wrong type
>  - Can't parse 'pt1'. Sequence item with index 0 has a wrong type
>  - Can't parse 'rec'. Expected sequence length 4, got 2
>  - Can't parse 'rec'. Expected sequence length 4, got 2

I compared "shapes2" annotations with my own and it seems to be nearly the same structure.

As example this is one file of my annotations.json:
[https://pastebin.com/XZMvAG6L](url)

You have an idea what the problem is here?
Thank for an advise

**Comment by joheras** [comment]
Hi,

Could you send me the four images used in the annotations.json file to
check what is wrong?

Best,
Jónathan

**Comment by Natriumpikant** [comment]
> Hi, Could you send me the four images used in the annotations.json file to check what is wrong? Best, Jónathan El vie, 30 sept 2022 a las 15:45, MSchanze ***@***.***>) escribió:
> […](#)

Good morning,

Thanks for your support.

Following the dataset i have used with 5 pictures:
_Done_

Regards

**Comment by joheras** [comment]
Hi,

The problem is related to the annotation since the element of bbox should
be integers instead of floats:

Instead of
"bbox": [
837.67,
122.48,
135.73,
221.82
],

It should be
"bbox": [
837,
122,
135,
221
],

I am preparing a new version of Clodsa to deal with that problem, but in
the meantime that is the solution.

Best,
Jónathan

**Comment by Natriumpikant** [comment]
> Hi, The problem is related to the annotation since the element of bbox should be integers instead of floats: Instead of "bbox": [ 837.67, 122.48, 135.73, 221.82 ], It should be "bbox": [ 837, 122, 135, 221 ], I am preparing a new version of Clodsa to deal with that problem, but in the meantime that is the solution. Best, Jónathan El lun, 3 oct 2022 a las 8:45, MSchanze ***@***.***>) 

Thank you!
