### ISSUE TITLE
Detection - Coco Output too much "[[]]"

### ISSUE THREAD

**Issue by Natriumpikant** [joheras/CLoDSA#76]
Hello again :)

Thanks for fixing my first issue.

While working in my coco-dataset i found another little issue:

**Input** Annotation File example:
`        {
            "id": 25,
            "image_id": 7,
            "category_id": 6,
            "iscrowd": 0,
            "area": 33020,
            "bbox": [
                315,
                907,
                130,
                254
            ],
            "segmentation": [],
            "width": 1080,
            "height": 1920
        },`

**Output** Annotation File example:
`        {
            "id": 26,
            "image_id": 7,
            "category_id": 13,
            "iscrowd": 0,
            "area": 34419,
            "bbox": [
                738,
                813,
                231,
                149
            ],
            "segmentation": [
                []
            ],
            "width": 1080,
            "height": 1920
        },`

Have a look at the second example(output) : **"segmentation": [[]]**

There is one of this **[]** too much. After pre-processing with Notepad++ and deleting at for every ID the coco file works well.
Maybe you want to fix this little issue.
Thanks for your work :)

**Comment by joheras** [comment]
Thanks. I will fix this issue in the new version of Clodsa that will be
released in the next few days.
Best,
Jónathan

**Comment by joheras** [comment]
It has been fixed in the new version of Clodsa.
Thanks,
Jónathan
