### ISSUE TITLE
Width and height no change after transform

### ISSUE THREAD

**Issue by vbnmzxc9513** [joheras/CLoDSA#9]
Hi,
After the Rotation of 90 and Cropping augmentation, my annotation is wrong with width and height. 
This is the part of code which reference the github. 
![image](https://user-images.githubusercontent.com/32253326/70865769-4323cb80-1f9c-11ea-91f5-973093d05022.png)
![image](https://user-images.githubusercontent.com/32253326/70865779-56cf3200-1f9c-11ea-8b6f-40a4af3938a7.png)

this is the cropping error when I training
![image](https://user-images.githubusercontent.com/32253326/70865856-1d4af680-1f9d-11ea-8577-24ea448a64bb.png)

Can anyone help me to fix this problem?
Thanks!

**Comment by joheras** [comment]
Hi, 

I am trying to reproduce the error, but I am not able to do it. 

In which kind of problem are you working?

I have created a small notebook in Colab trying to reproduce the problem with your code:
https://colab.research.google.com/drive/1gmwox5pBd-w_XwZQRyrzzW1jZtujK57A

Could you modify that notebook with your code to see what is going on?

Best,
Jónathan

**Comment by vbnmzxc9513** [comment]
Thanks for your reply,

My problem type is "instance_segmentation".
This is my code fixing from your notebook code. And I got the same results.
[PossibleError.zip](https://github.com/joheras/CLoDSA/files/3967169/PossibleError.zip)

ex. This is a set of results.
![image](https://user-images.githubusercontent.com/32253326/70895961-cee43900-202a-11ea-9c9d-204ab02d16ef.png)

But the annotation informations are wrong with them.
![image](https://user-images.githubusercontent.com/32253326/70896099-1074e400-202b-11ea-86ad-0b4efa7a5aad.png)

In the raw dataset annotation, I didn't give "info" and "licenses" information, the other information is all right. Is this the problem of work?
![image](https://user-images.githubusercontent.com/32253326/70896350-7fead380-202b-11ea-9bdb-54bdad4a35e4.png)
Thanks

**Comment by joheras** [comment]
I think that I have fixed the problem. Could you check whether it works properly now? 
You have to upload your clodsa version:
pip install clodsa==1.2.37

**Comment by vbnmzxc9513** [comment]
I have tried again and it worked very well!
This library is very useful and excellent!
Thank you very much!!

**Comment by joheras** [comment]
Great. Let me know if you need further help.
Best,
Jónathan
